name: Test Flask Application

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
        options: --health-cmd="redis-server --test-memory 1" --health-interval=30s --health-retries=3 --health-start-period=10s --health-timeout=5s

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Set up Docker cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Build and start services
        run: docker-compose up --build -d

      - name: Wait for services to be ready
        run: |
          echo "Waiting for Redis and Flask application to be ready..."
          sleep 10
          until curl --silent --fail http://localhost:8000/health; do
            echo "Waiting for health check..."
            sleep 5
          done

      - name: Verify /health endpoint
        run: |
          curl --silent --fail http://localhost:8000/health
          echo "Health check passed!"

      - name: Clean up
        run: docker-compose down
